# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    -   id: flake8
        args: ["src"]
-   repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
    -   id: black
        language_version: python3 # Should be a command that runs python3.6+
-   repo: https://github.com/Yelp/detect-secrets
    rev: v0.14.3
    hooks:
    -   id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: .*/tests/.*
-   repo: https://github.com/aflc/pre-commit-jupyter
    rev: master
    hooks:
    -   id: jupyter-notebook-cleanup
        args:
        -   --remove-kernel-metadata
        -   --pin-patterns
        -   "[keep_output]"
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-added-large-files
        args: ["--maxkb=5120"]
    -   id: end-of-file-fixer
        exclude: '\.Rd'
    -   id: trailing-whitespace
